### PR TITLE
Adding devcontainers support

### PR DESCRIPTION
**Pull request by jabrena**
Adding Devcontainers support to unify the way to test the project.

### CODE REVIEW

**Comment by jabrena** [comment]
Signed

**Comment by SylvainJuge** [comment]
Hi @jabrena , thanks for you PR.

I am not familiar with devcontainers, what are the benefits of using it in the context of this project ?

The reason I am asking is that this is mostly a sample application that we use for testing the APM agent at Elastic, thus we rarely have to run/debug it within containers, and we do most of our dev work with plain shell and InteliJ.

For non-Elastic developers, there is a huge variety of tools and we can't handle and maintain all the different ways to run and tinker in the application code.

As a consequence, while we might add this to the project it will likely become state and not be maintained over time, so I think it would be better if we leave it as-is for now. However I'd be happy to learn that we are missing something here.

**Comment by jabrena** [comment]
Hi @SylvainJuge 

I would like to explain the motivation to use DevContainers as another alternative to the classic local dev environment. Using the traditional approach you are coupled to one OS and a particular computer enviroment but using a Cloud environment, everytime that you use Codespaces, you create a clean enviroment with a particular Java version and the whole enviroment is clean so the build is more predictible.

In the other hand, the PR is only a configuration so the PR doesn´t add any side effect to the repo, you could continue developing or testing in a classic way or give a try to Codespaces.

In the another hand if you like the arguments and you merge, I would like to make more questions about the repo and collaborate more. I am using ELK :) 

Juan Antonio

**Comment by SylvainJuge** [comment]
Hi @jabrena , 

I understand your intent here, but I think it's better for now if we don't add this file and will close this PR.
- this is just a simple test application, not something that is actively developed nor which often requires new features or modifications, hence the need to "make anyone contribution easier" is a bit less relevant on this type of project.
- this file will get stale very quickly as the team in charge of it won't use it, so it's usually better to only keep the codebase with the strict minimum required, no more, no less.
- I understand that adding it won't cause any side effects, but in the near future it will be hard to explain why it's there or why it could be used for, this sounds a bit cliché but the job of maintaining software as much about "removing things and keeping them simple" as "adding new features and new stuff", usually the simpler the easier it is to maintain.
- Elastic has >500 public repositories, so doing this at scale just won't work.

Of course, that would be completely different if it was a more "real" application where we would expect plenty of contributions, but that's not the case here.

If you really need to use devcontainers with a similar project, I think it would be simpler to find a way to use an external file into the project directory, here are a few ideas that usually work:
- directly forking this repository, add your own file in your fork and merge changes from upstream from time to time.
- find in the `devcontainers` if there is a way to use a file outside of the project directory
- using symbolic links to implement the solution above (even doable on windows these days)
- using git submodules and aggregate two (or more) git repositories into one project

**Pull request closed without merging**
